# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 097279fd06c7c2fa479479492ffb2e48156f4ae780d0a31ab191f184ff4da695d3177843d8313e34e87fa31568170ac5a8d396b8ec7dc973d7fa8937c7605fa7

test:
  secret_key_base: 3554e9ad3337fd6357cebebc9ea3f1cae2d66389e7bd583bad401db81d4c4d2c4a27c6d934cadaf93e89b616732f6d46d91762fcf1127108ad68be67a2b24246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
